### ISSUE TITLE
Download latest Freedom Studio version without account

### ISSUE THREAD

**Issue by nandlab** [sifive/freedom-studio#4]
I am considering to get started with a RISC-V development board. Is there a way to download the latest Freedom Studio for Linux without signing up or submitting any personal information? I think this should be possible. I do not see the latest version in the GitHub releases.

Is Freedom Studio even an open source project and can it be build manually? This git repo contains only a readme.

**Comment by mtuxpe** [comment]
https://github.com/sifive/freedom-studio/releases/tag/v2020.11.1

**Comment by DecodeTheEncoded** [comment]
> https://github.com/sifive/freedom-studio/releases/tag/v2020.11.1

It's not there anymore. The sifive software site has evolved drastically recently. Is there a valid way to download the latest freedom studio version?

**Comment by honi** [comment]
I created an account at SiFive.com but I can't find any download link to Freedom Studio within the SCS portal. Also, latest release on github just contains the [README](https://github.com/sifive/freedom-studio/blob/master/README.md) file.

Found this link from what I believe is the old website: https://d2pn104n81t9m2.cloudfront.net/products/tools/
